
name: Obi Test

on:
  push:
    branches:
      - feature/obi

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: SSH into EC2 instance and deploy container
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_IP }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.EC2_PASSWORD }}
        script: |
          docker pull $ECR_REGISTRY/onebillionideas:${IMAGE_TAG}
          docker stop my-docker-container || true
          docker rm my-docker-container || true
          docker run -d -p 8080:8080 $ECR_REGISTRY/onebillionideas:${IMAGE_TAG}"
